In [175]:
import numpy as np

In [176]:
TEST = 1
if TEST==1:
    dim = [3,2]
    pos0 = [1,1]
    pos1 = [2,1]
    max_dist = 4
else:
    dim = [300, 275]
    pos0 = [150, 150]
    pos1 = [185, 100]
    max_dist = 500

In [177]:
(width, height) = dim
(x0,y0) = pos0
(x1,y1) = pos1

#   Generate index arrays
#   This could be done a little more efficiently, but this is readable
nx_max = 1 + np.floor((max_dist+x0)/(2*width))
ny_max = 1 + np.floor((max_dist+y0)/(2*width))
nx = np.arange(-nx_max, nx_max+1)
ny = np.arange(-ny_max, ny_max+1)

In [178]:

sgn = np.array([1, -1]).reshape((-1,1))

#   Replicated my positions
X0 = (2*nx*width + sgn*x0).flatten()
Y0 = (2*ny*height + sgn*y0).flatten()

#   Replicated trainer positions
X1 = (2*nx*width + sgn*x1).flatten()
Y1 = (2*ny*height + sgn*y1).flatten()

#   Only keep those within square of size 2*dist
indx = (abs(X0-x0)<=max_dist) & (abs(X1-x0)<=max_dist)
indy = (abs(Y0-y0)<=max_dist) & (abs(Y1-y0)<=max_dist)

#   Generate meshgrid
(X0, Y0) = np.meshgrid(X0[indx], Y0[indy])
(X1, Y1) = np.meshgrid(X1[indx], Y1[indy])
X0 = X0.flatten()
Y0 = Y0.flatten()
X1 = X1.flatten()
Y1 = Y1.flatten()
print(np.vstack((X0, Y0, X1, Y1)))


[[ 1. -1.  5.  1. -1.  5.  1. -1.  5.  1. -1.  5.  1. -1.  5.]
 [-3. -3. -3.  1.  1.  1.  5.  5.  5. -1. -1. -1.  3.  3.  3.]
 [ 2. -2.  4.  2. -2.  4.  2. -2.  4.  2. -2.  4.  2. -2.  4.]
 [-3. -3. -3.  1.  1.  1.  5.  5.  5. -1. -1. -1.  3.  3.  3.]]


In [179]:

#   Calculate square distances
dX0 = X0-x0
dY0 = Y0-y0
dX1 = X1-x0
dY1 = Y1-y0
d20 = dX0**2 + dY0**2
d21 = dX1**2 + dY1**2
print(np.vstack((d20, d21)))

[[16. 20. 32.  0.  4. 16. 16. 20. 32.  4.  8. 20.  4.  8. 20.]
 [17. 25. 25.  1.  9.  9. 17. 25. 25.  5. 13. 13.  5. 13. 13.]]


In [180]:
    #   Calculate tan(theta) = y/x
    th0 = dY0/dX0
    th1 = dY1/dX1

D:\miniconda3\envs\Foobar\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in divide
  
D:\miniconda3\envs\Foobar\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in divide
  


In [181]:

#   Get indices where:
#       tan(theta0)=y0/x0 == tan(theta1)=y1/x1 --> x0*y1 != x1*y0
#       and d21<d20
ind1a = ( ((dX0.reshape((-1,1))) * dY1-y1) == ((dY0.reshape((-1,1))) * dX1-x1))
print(1*ind1a)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [182]:
ind1b = (((dY0/dX0).reshape((-1,1)))==(dY1/dX1))
print(1*ind1b)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


D:\miniconda3\envs\Foobar\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in divide
  """Entry point for launching an IPython kernel.
D:\miniconda3\envs\Foobar\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in divide
  """Entry point for launching an IPython kernel.


In [183]:
ind2 = ((d20.reshape((-1,1)))<=d21)
print(1*ind2)

[[1 1 1 0 0 0 1 1 1 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 0 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 0 0 0 1 1 1 0 0 0 0 0 0]
 [1 1 1 0 0 0 1 1 1 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 0 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 0 1 1 1 1 1 0 1 1 0 1 1]
 [0 1 1 0 0 0 0 1 1 0 0 0 0 0 0]
 [1 1 1 0 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 0 1 1 1 1 1 0 1 1 0 1 1]
 [0 1 1 0 0 0 0 1 1 0 0 0 0 0 0]]


In [184]:
ind = np.bitwise_not(np.any(
    ((th0.reshape((-1,1)))==th1)
    & ((d20.reshape((-1,1)))<=d21), axis=0)) & (d21<=(max_dist**2))

print(1-(ind))

[1 1 1 0 1 1 1 1 1 0 0 0 0 0 0]


In [185]:
print(th1.shape)
print(th1)


(15L,)
[-4.          1.33333333 -1.33333333  0.         -0.          0.
  4.         -1.33333333  1.33333333 -2.          0.66666667 -0.66666667
  2.         -0.66666667  0.66666667]


In [186]:
print(th1[ind])


[ 0.         -2.          0.66666667 -0.66666667  2.         -0.66666667
  0.66666667]


In [187]:
_, count = np.unique(th1[ind], return_counts=True)
print(count)

[1 2 1 2 1]
